// @ts-nocheck
// Seed data for EventGo — 30 curated events + 3 featured + 3 upcoming (home page)
// All events are pre-approved for display

export const seedEvents = [
  // ── Featured Events (shown on home hero carousel) ──
  {
    id: "event_featured_1",
    title: "Kokkola Winter Accordion 2026",
    description: "Come and enjoy Valentine's Day, music, and being together. The K30 orchestra, Jazzcombo, accordion groups, and many others will be performing at the Koivuhaka shopping center.",
    category: "Music",
    tags: ["accordion", "orchestra", "live-music"],
    startDate: "2026-02-14",
    endDate: null,
    startTime: "12:00",
    endTime: "14:00",
    venueName: "Koivuhaka Shopping Center",
    address: "",
    city: "Kokkola",
    pricingType: "free",
    price: null,
    capacity: "300",
    coverImage: null,
    organizerName: "Kokkola Cultural Society",
    organizerEmail: "culture@kokkola.fi",
    organizerPhone: "+358 40 123 4567",
    website: "",
    status: "approved",
    featured: true,
    attendees: 0,
    createdAt: "2026-01-15T10:00:00.000Z",
  },
  {
    id: "event_featured_2",
    title: "Summer Sounds Festival 2026",
    description: "Experience an unforgettable evening of live music under the stars. Featuring top artists from across Scandinavia, food trucks, and an electric atmosphere.",
    category: "Festival",
    tags: ["summer", "live-music", "outdoor"],
    startDate: "2026-06-19",
    endDate: null,
    startTime: "16:00",
    endTime: "23:00",
    venueName: "Seurasaari Island",
    address: "",
    city: "Helsinki",
    pricingType: "paid",
    price: "42",
    capacity: "1500",
    coverImage: "https://images.unsplash.com/photo-1573463908761-567b9356c64f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvdXRkb29yJTIwbXVzaWMlMjBmZXN0aXZhbCUyMHN0YWdlfGVufDF8fHx8MTc3MTg0ODYxN3ww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Nordic Events Oy",
    organizerEmail: "info@nordicevent.fi",
    organizerPhone: "+358 50 555 1234",
    website: "https://summersounds.fi",
    status: "approved",
    featured: true,
    attendees: 0,
    createdAt: "2026-01-20T10:00:00.000Z",
  },
  {
    id: "event_featured_3",
    title: "Nordic Contemporary Art Expo",
    description: "Discover cutting-edge works from emerging Nordic artists. This curated exhibition explores themes of identity, nature, and technology.",
    category: "Art",
    tags: ["contemporary", "exhibition", "nordic"],
    startDate: "2026-03-07",
    endDate: null,
    startTime: "10:00",
    endTime: "18:00",
    venueName: "Kiasma Museum",
    address: "",
    city: "Helsinki",
    pricingType: "paid",
    price: "18",
    capacity: "500",
    coverImage: "https://images.unsplash.com/photo-1761403757058-e3c95b662a89?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcnQlMjBnYWxsZXJ5JTIwZXhoaWJpdGlvbiUyMG1vZGVybnxlbnwxfHx8fDE3NzE5MDIzOTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Kiasma Foundation",
    organizerEmail: "info@kiasma.fi",
    organizerPhone: "",
    website: "https://kiasma.fi",
    status: "approved",
    featured: true,
    attendees: 0,
    createdAt: "2026-01-22T10:00:00.000Z",
  },

  // ── Browse / Upcoming events ──
  {
    id: "event_001",
    title: "Helsinki Jazz Night",
    description: "An enchanting evening of jazz classics and modern improvisation at Helsinki's most intimate jazz venue. Featuring local and international talent.",
    category: "Music",
    tags: ["jazz", "nightlife", "live"],
    startDate: "2026-03-06",
    endDate: null,
    startTime: "20:00",
    endTime: "23:30",
    venueName: "Storyville Jazz Club",
    address: "",
    city: "Helsinki",
    pricingType: "paid",
    price: "25",
    capacity: "150",
    coverImage: "https://images.unsplash.com/photo-1761019362913-9cf17b5a0101?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxqYXp6JTIwY29uY2VydCUyMG5pZ2h0Y2x1YnxlbnwxfHx8fDE3NzE5NTcyNzJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Storyville Events",
    organizerEmail: "events@storyville.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "event_002",
    title: "Nordic Street Food Festival",
    description: "Taste the best street food from around the Nordics. Over 40 vendors offering everything from Finnish salmon to Swedish meatballs and Danish pastries.",
    category: "Food & Drink",
    tags: ["food", "street-food", "outdoor"],
    startDate: "2026-03-21",
    endDate: null,
    startTime: "11:00",
    endTime: "20:00",
    venueName: "Tori Square",
    address: "",
    city: "Turku",
    pricingType: "free",
    price: null,
    capacity: "500",
    coverImage: "https://images.unsplash.com/photo-1662899311670-7e6bbe986166?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb29kJTIwbWFya2V0JTIwc3RhbGxzfGVufDF8fHx8MTc3MTkxNjEzNnww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Turku Food Council",
    organizerEmail: "info@turkufood.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-11T10:00:00.000Z",
  },
  {
    id: "event_003",
    title: "FutureTech Summit 2026",
    description: "Join 800+ innovators, entrepreneurs, and tech leaders for a day of keynotes, workshops, and networking. Topics include AI, blockchain, and green tech.",
    category: "Tech",
    tags: ["technology", "conference", "AI"],
    startDate: "2026-04-13",
    endDate: null,
    startTime: "09:00",
    endTime: "18:00",
    venueName: "Messukeskus Expo Centre",
    address: "",
    city: "Helsinki",
    pricingType: "paid",
    price: "89",
    capacity: "1000",
    coverImage: "https://images.unsplash.com/photo-1592758080692-b6a5dbe9c725?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWNoJTIwY29uZmVyZW5jZSUyMHN0YWdlfGVufDF8fHx8MTc3MTg5NDM3M3ww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "FutureTech Finland",
    organizerEmail: "summit@futuretech.fi",
    organizerPhone: "",
    website: "https://futuretech.fi",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-12T10:00:00.000Z",
  },
  {
    id: "event_004",
    title: "Sunrise Yoga in the Park",
    description: "Start your Sunday with a peaceful outdoor yoga session. Suitable for all levels, mats provided. End with guided meditation and herbal tea.",
    category: "Wellness",
    tags: ["yoga", "outdoor", "meditation"],
    startDate: "2026-05-10",
    endDate: null,
    startTime: "07:00",
    endTime: "08:30",
    venueName: "Esplanadi Park",
    address: "",
    city: "Helsinki",
    pricingType: "free",
    price: null,
    capacity: "80",
    coverImage: "https://images.unsplash.com/photo-1608405059861-b21a68ae76a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b2dhJTIwY2xhc3MlMjBvdXRkb29yfGVufDF8fHx8MTc3MTk1NzI3MXww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Helsinki Wellness Co",
    organizerEmail: "hello@helsinkiwellness.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-13T10:00:00.000Z",
  },
  {
    id: "event_005",
    title: "Finnish Wine & Cheese Tasting",
    description: "An exclusive evening exploring artisan Finnish wines paired with carefully curated cheeses. Guided by sommelier Annika Virtanen.",
    category: "Food & Drink",
    tags: ["wine", "tasting", "artisan"],
    startDate: "2026-03-19",
    endDate: null,
    startTime: "18:00",
    endTime: "21:00",
    venueName: "Viinitori Cellar",
    address: "",
    city: "Tampere",
    pricingType: "paid",
    price: "45",
    capacity: "40",
    coverImage: "https://images.unsplash.com/photo-1633338001234-63ede6a2c0e9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aW5lJTIwdGFzdGluZyUyMHZpbmV5YXJkfGVufDF8fHx8MTc3MTkzMjY1MHww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Viinitori Events",
    organizerEmail: "events@viinitori.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-14T10:00:00.000Z",
  },
  {
    id: "event_006",
    title: "Kokkola City Marathon",
    description: "Run through the scenic streets and coastal paths of Kokkola. Full marathon, half marathon, and 10K options available. Chip timing included.",
    category: "Sports",
    tags: ["marathon", "running", "fitness"],
    startDate: "2026-05-30",
    endDate: null,
    startTime: "09:00",
    endTime: "15:00",
    venueName: "City Centre",
    address: "",
    city: "Kokkola",
    pricingType: "paid",
    price: "35",
    capacity: "600",
    coverImage: "https://images.unsplash.com/photo-1760315972424-1637530daead?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYXJhdGhvbiUyMHJ1bm5lcnMlMjBjaXR5fGVufDF8fHx8MTc3MTkyNzk0M3ww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Kokkola Sports Association",
    organizerEmail: "marathon@kokkola.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-15T10:00:00.000Z",
  },
  {
    id: "event_007",
    title: "Nordic Indie Film Festival",
    description: "Three days of independent cinema from Scandinavia and the Baltics. Q&A sessions with directors after every screening.",
    category: "Art",
    tags: ["film", "cinema", "indie"],
    startDate: "2026-04-08",
    endDate: null,
    startTime: "14:00",
    endTime: "22:00",
    venueName: "Bio Rex Cinema",
    address: "",
    city: "Vaasa",
    pricingType: "paid",
    price: "18",
    capacity: "250",
    coverImage: "https://images.unsplash.com/photo-1702890764798-eda71e941da1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmaWxtJTIwZmVzdGl2YWwlMjBjaW5lbWF8ZW58MXx8fHwxNzcxOTU3MjczfDA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Nordic Film Society",
    organizerEmail: "film@nordicfilm.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-16T10:00:00.000Z",
  },
  {
    id: "event_008",
    title: "Ceramic Pottery Workshop",
    description: "Learn the fundamentals of wheel-throwing pottery in this hands-on workshop. All materials included. Take home your own creation!",
    category: "Workshop",
    tags: ["pottery", "ceramics", "handmade"],
    startDate: "2026-03-28",
    endDate: null,
    startTime: "10:00",
    endTime: "13:00",
    venueName: "Käsityöpaja Studio",
    address: "",
    city: "Oulu",
    pricingType: "paid",
    price: "40",
    capacity: "20",
    coverImage: "https://images.unsplash.com/photo-1763824372117-1ff339b522e9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3R0ZXJ5JTIwd29ya3Nob3AlMjBoYW5kbWFkZXxlbnwxfHx8fDE3NzE5NTcyNzR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Oulu Craft Studio",
    organizerEmail: "studio@oulucrafts.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-17T10:00:00.000Z",
  },
  {
    id: "event_009",
    title: "Stand-Up Comedy Open Mic",
    description: "A night of laughs with emerging and established comedians. Open mic spots available — sign up at the door!",
    category: "Comedy",
    tags: ["comedy", "standup", "nightlife"],
    startDate: "2026-03-20",
    endDate: null,
    startTime: "19:30",
    endTime: "22:00",
    venueName: "Kulttuuriklubi",
    address: "",
    city: "Jyväskylä",
    pricingType: "paid",
    price: "12",
    capacity: "100",
    coverImage: "https://images.unsplash.com/photo-1728674114827-e34c17a67534?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGFuZCUyMHVwJTIwY29tZWR5JTIwc3RhZ2V8ZW58MXx8fHwxNzcxOTU3Mjc0fDA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Laugh Factory Finland",
    organizerEmail: "info@laughfactory.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-18T10:00:00.000Z",
  },
  {
    id: "event_010",
    title: "Helsinki Book Fair 2026",
    description: "Finland's largest literary event. Meet authors, attend book signings, panel discussions, and discover new releases across all genres.",
    category: "Art",
    tags: ["books", "literature", "fair"],
    startDate: "2026-04-25",
    endDate: null,
    startTime: "10:00",
    endTime: "18:00",
    venueName: "Helsinki Expo Centre",
    address: "",
    city: "Helsinki",
    pricingType: "free",
    price: null,
    capacity: "1500",
    coverImage: "https://images.unsplash.com/photo-1660606422336-4dd7b6795838?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib29rJTIwZmFpciUyMGxpYnJhcnl8ZW58MXx8fHwxNzcxOTUxNTcxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Helsinki Book Society",
    organizerEmail: "fair@helsinkibooks.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-19T10:00:00.000Z",
  },
  {
    id: "event_011",
    title: "Finnish National Ballet Gala",
    description: "A spectacular evening of classical and contemporary ballet performed by Finland's finest dancers at the iconic Finnish National Opera House.",
    category: "Art",
    tags: ["ballet", "dance", "performance"],
    startDate: "2026-04-18",
    endDate: null,
    startTime: "19:00",
    endTime: "21:30",
    venueName: "Finnish National Opera",
    address: "",
    city: "Helsinki",
    pricingType: "paid",
    price: "55",
    capacity: "500",
    coverImage: "https://images.unsplash.com/photo-1686435386310-92ee42a3580f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkYW5jZSUyMHBlcmZvcm1hbmNlJTIwYmFsbGV0fGVufDF8fHx8MTc3MTk1NzI3NXww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Finnish National Opera",
    organizerEmail: "tickets@opera.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-20T10:00:00.000Z",
  },
  {
    id: "event_012",
    title: "Arctic Light Photography Exhibit",
    description: "Stunning photographs capturing the aurora borealis, midnight sun, and Arctic landscapes of Finnish Lapland. Meet the photographers at the opening night.",
    category: "Art",
    tags: ["photography", "arctic", "exhibition"],
    startDate: "2026-03-02",
    endDate: null,
    startTime: "10:00",
    endTime: "17:00",
    venueName: "Kiasma Museum",
    address: "",
    city: "Helsinki",
    pricingType: "paid",
    price: "15",
    capacity: "200",
    coverImage: "https://images.unsplash.com/photo-1742497359858-8e0a442c9c55?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaG90b2dyYXBoeSUyMGV4aGliaXRpb24lMjBnYWxsZXJ5fGVufDF8fHx8MTc3MTk1NzI3NXww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Kiasma Foundation",
    organizerEmail: "info@kiasma.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-21T10:00:00.000Z",
  },
  {
    id: "event_013",
    title: "Startup Pitch Night",
    description: "Watch 12 Finnish startups pitch to a panel of VCs and angel investors. Network with founders and investors afterwards.",
    category: "Tech",
    tags: ["startup", "pitch", "networking"],
    startDate: "2026-03-11",
    endDate: null,
    startTime: "17:00",
    endTime: "20:00",
    venueName: "Maria 01 Campus",
    address: "",
    city: "Helsinki",
    pricingType: "free",
    price: null,
    capacity: "250",
    coverImage: "https://images.unsplash.com/photo-1599592187465-6dc742367282?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGFydHVwJTIwcGl0Y2glMjBwcmVzZW50YXRpb258ZW58MXx8fHwxNzcxOTU3Mjc2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Maria 01",
    organizerEmail: "events@maria.io",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-22T10:00:00.000Z",
  },
  {
    id: "event_014",
    title: "Spring Farmers Market",
    description: "Fresh produce, organic foods, handmade goods, and artisan crafts. Support local farmers and producers.",
    category: "Food & Drink",
    tags: ["farmers-market", "organic", "local"],
    startDate: "2026-04-04",
    endDate: null,
    startTime: "08:00",
    endTime: "14:00",
    venueName: "Hakaniemi Market Hall",
    address: "",
    city: "Helsinki",
    pricingType: "free",
    price: null,
    capacity: "800",
    coverImage: "https://images.unsplash.com/photo-1747503331142-27f458a1498c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXJtZXJzJTIwbWFya2V0JTIwZnJlc2glMjBwcm9kdWNlfGVufDF8fHx8MTc3MTk1NzI3Nnww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Helsinki Market Association",
    organizerEmail: "info@hakaniemimarket.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-23T10:00:00.000Z",
  },
  {
    id: "event_015",
    title: "Sibelius Symphony Evening",
    description: "The Helsinki Philharmonic performs Sibelius's greatest symphonies in the magnificent Finlandia Hall.",
    category: "Music",
    tags: ["classical", "symphony", "sibelius"],
    startDate: "2026-03-27",
    endDate: null,
    startTime: "19:00",
    endTime: "21:00",
    venueName: "Finlandia Hall",
    address: "",
    city: "Helsinki",
    pricingType: "paid",
    price: "38",
    capacity: "400",
    coverImage: "https://images.unsplash.com/photo-1519683000900-034603c717b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjbGFzc2ljYWwlMjBvcmNoZXN0cmElMjBzeW1waG9ueXxlbnwxfHx8fDE3NzE5NDIxOTZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Helsinki Philharmonic",
    organizerEmail: "tickets@helsinkiphilharmonic.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-24T10:00:00.000Z",
  },
  {
    id: "event_016",
    title: "Nuuksio National Park Hike",
    description: "Guided group hike through the beautiful trails of Nuuksio. Campfire lunch included. All fitness levels welcome.",
    category: "Outdoor",
    tags: ["hiking", "nature", "forest"],
    startDate: "2026-05-17",
    endDate: null,
    startTime: "08:00",
    endTime: "15:00",
    venueName: "Nuuksio National Park",
    address: "",
    city: "Espoo",
    pricingType: "free",
    price: null,
    capacity: "50",
    coverImage: "https://images.unsplash.com/photo-1600346774255-f8e8d0b33309?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvdXRkb29yJTIwaGlraW5nJTIwdHJhaWx8ZW58MXx8fHwxNzcxODY2OTgyfDA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Nature Finland",
    organizerEmail: "hikes@naturefinland.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-25T10:00:00.000Z",
  },
  {
    id: "event_017",
    title: "Craft Beer & Sauna Festival",
    description: "Combine Finnish sauna culture with craft beer tasting. Over 25 local breweries, live music, and authentic wood-fired saunas.",
    category: "Food & Drink",
    tags: ["beer", "sauna", "festival"],
    startDate: "2026-06-06",
    endDate: null,
    startTime: "14:00",
    endTime: "22:00",
    venueName: "Sompasauna",
    address: "",
    city: "Helsinki",
    pricingType: "paid",
    price: "30",
    capacity: "350",
    coverImage: "https://images.unsplash.com/photo-1698369778928-9153537f1c2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcmFmdCUyMGJlZXIlMjBmZXN0aXZhbHxlbnwxfHx8fDE3NzE5NTcyNzd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Helsinki Beer Society",
    organizerEmail: "festival@helsinkibeer.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-26T10:00:00.000Z",
  },
  {
    id: "event_018",
    title: "Family Fun Day Carnival",
    description: "A magical day for the whole family with rides, games, face painting, magic shows, and cotton candy at the legendary Linnanmäki.",
    category: "Kids",
    tags: ["family", "carnival", "kids"],
    startDate: "2026-05-24",
    endDate: null,
    startTime: "10:00",
    endTime: "17:00",
    venueName: "Linnanmäki",
    address: "",
    city: "Helsinki",
    pricingType: "paid",
    price: "15",
    capacity: "800",
    coverImage: "https://images.unsplash.com/photo-1707696544753-cf8af7babeee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxraWRzJTIwcGxheWdyb3VuZCUyMGNhcm5pdmFsfGVufDF8fHx8MTc3MTk1NzI3N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Linnanmäki Foundation",
    organizerEmail: "info@linnanmaki.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-27T10:00:00.000Z",
  },
  {
    id: "event_019",
    title: "Watercolor Painting Workshop",
    description: "Learn watercolor techniques from professional artist Liisa Mäkelä. All supplies provided. Perfect for beginners.",
    category: "Workshop",
    tags: ["painting", "art", "creative"],
    startDate: "2026-03-14",
    endDate: null,
    startTime: "11:00",
    endTime: "14:00",
    venueName: "ArtHub Studio",
    address: "",
    city: "Turku",
    pricingType: "paid",
    price: "35",
    capacity: "20",
    coverImage: "https://images.unsplash.com/photo-1615502732093-495f92575863?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWludGluZyUyMGNsYXNzJTIwYXJ0JTIwc3R1ZGlvfGVufDF8fHx8MTc3MTk1NzI3OHww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "ArtHub Turku",
    organizerEmail: "workshops@arthub.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-28T10:00:00.000Z",
  },
  {
    id: "event_020",
    title: "Urban Skate Jam",
    description: "Skateboarding competition and jam session at Helsinki's best skatepark. Live DJ, prizes, and food vendors.",
    category: "Sports",
    tags: ["skateboarding", "urban", "competition"],
    startDate: "2026-06-13",
    endDate: null,
    startTime: "12:00",
    endTime: "18:00",
    venueName: "Suvilahti Skatepark",
    address: "",
    city: "Helsinki",
    pricingType: "free",
    price: null,
    capacity: "200",
    coverImage: "https://images.unsplash.com/photo-1761772595737-49723cdeabee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxza2F0ZWJvYXJkJTIwcGFyayUyMHVyYmFufGVufDF8fHx8MTc3MTg1Nzc3OXww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Helsinki Skate Club",
    organizerEmail: "jam@helsinkiskate.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-29T10:00:00.000Z",
  },
  {
    id: "event_021",
    title: "Future of Science Exhibition",
    description: "Interactive science exhibition featuring VR space exploration, robotics demos, and hands-on experiments for all ages.",
    category: "Tech",
    tags: ["science", "exhibition", "interactive"],
    startDate: "2026-03-09",
    endDate: null,
    startTime: "10:00",
    endTime: "16:00",
    venueName: "Heureka Science Centre",
    address: "",
    city: "Vantaa",
    pricingType: "paid",
    price: "22",
    capacity: "500",
    coverImage: "https://images.unsplash.com/photo-1764253340521-c920fd89a66e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzY2llbmNlJTIwbXVzZXVtJTIwZXhoaWJpdHxlbnwxfHx8fDE3NzE5NTcyNzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Heureka Foundation",
    organizerEmail: "info@heureka.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-01-30T10:00:00.000Z",
  },
  {
    id: "event_022",
    title: "Acoustic Campfire Sessions",
    description: "Intimate acoustic performances around a campfire. Bring your own instrument or just enjoy the music under the midnight sun.",
    category: "Music",
    tags: ["acoustic", "campfire", "outdoor"],
    startDate: "2026-06-05",
    endDate: null,
    startTime: "20:00",
    endTime: "23:00",
    venueName: "Rastila Camping",
    address: "",
    city: "Helsinki",
    pricingType: "free",
    price: null,
    capacity: "80",
    coverImage: "https://images.unsplash.com/photo-1758272960116-93c2a2463e42?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhY291c3RpYyUyMGd1aXRhciUyMGNhbXBmaXJlfGVufDF8fHx8MTc3MTg3MDg4NHww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Helsinki Music Collective",
    organizerEmail: "campfire@hmc.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-02-01T10:00:00.000Z",
  },
  {
    id: "event_023",
    title: "Spring Garden Festival",
    description: "Celebrate the arrival of spring at Kaisaniemi Botanic Garden with guided tours, plant workshops, and family activities.",
    category: "Festival",
    tags: ["garden", "spring", "botanical"],
    startDate: "2026-05-03",
    endDate: null,
    startTime: "09:00",
    endTime: "16:00",
    venueName: "Kaisaniemi Botanic Garden",
    address: "",
    city: "Helsinki",
    pricingType: "free",
    price: null,
    capacity: "600",
    coverImage: "https://images.unsplash.com/photo-1648992137572-02d9646bbbda?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmbG93ZXIlMjBnYXJkZW4lMjBzcHJpbmd8ZW58MXx8fHwxNzcxODk4OTIxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Helsinki Parks Department",
    organizerEmail: "parks@helsinki.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-02-02T10:00:00.000Z",
  },
  {
    id: "event_024",
    title: "City Basketball Tournament",
    description: "3v3 street basketball tournament open to all skill levels. Prizes for winners, live music, and food trucks.",
    category: "Sports",
    tags: ["basketball", "tournament", "street"],
    startDate: "2026-04-11",
    endDate: null,
    startTime: "10:00",
    endTime: "18:00",
    venueName: "Pirkkola Sports Hall",
    address: "",
    city: "Helsinki",
    pricingType: "paid",
    price: "10",
    capacity: "350",
    coverImage: "https://images.unsplash.com/photo-1659523888759-e76c7ba5a030?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXNrZXRiYWxsJTIwdG91cm5hbWVudCUyMGd5bXxlbnwxfHx8fDE3NzE5NTcyODB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Helsinki Basketball Association",
    organizerEmail: "tournament@helsinkibasket.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-02-03T10:00:00.000Z",
  },
  {
    id: "event_025",
    title: "Nordic Cooking Masterclass",
    description: "Master the art of Nordic cuisine with Chef Mikko Lahti. Learn to prepare traditional Finnish dishes with a modern twist.",
    category: "Workshop",
    tags: ["cooking", "nordic", "masterclass"],
    startDate: "2026-03-22",
    endDate: null,
    startTime: "11:00",
    endTime: "15:00",
    venueName: "Kitchen Academy",
    address: "",
    city: "Espoo",
    pricingType: "paid",
    price: "65",
    capacity: "30",
    coverImage: "https://images.unsplash.com/photo-1762994576926-b8268190a2c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb29raW5nJTIwY2xhc3MlMjBraXRjaGVufGVufDF8fHx8MTc3MTk1NDEyN3ww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Kitchen Academy Finland",
    organizerEmail: "classes@kitchenacademy.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-02-04T10:00:00.000Z",
  },
  {
    id: "event_026",
    title: "Baltic Surf Camp",
    description: "Learn to surf on the Baltic Sea! Beginner-friendly camp with professional instructors, wetsuit and board rental included.",
    category: "Sports",
    tags: ["surfing", "water-sports", "camp"],
    startDate: "2026-06-15",
    endDate: null,
    startTime: "08:00",
    endTime: "12:00",
    venueName: "Yyteri Beach",
    address: "",
    city: "Pori",
    pricingType: "paid",
    price: "50",
    capacity: "50",
    coverImage: "https://images.unsplash.com/photo-1613486185528-d9b0ae83f008?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXJmaW5nJTIwYmVhY2glMjB3YXZlc3xlbnwxfHx8fDE3NzE5NTcyODB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Baltic Surf School",
    organizerEmail: "camp@balticsurf.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-02-05T10:00:00.000Z",
  },
  {
    id: "event_027",
    title: "Street Art Walking Tour",
    description: "Guided walking tour through Helsinki's vibrant Kallio district. Discover hidden murals, graffiti, and the stories behind them.",
    category: "Art",
    tags: ["street-art", "walking-tour", "urban"],
    startDate: "2026-03-29",
    endDate: null,
    startTime: "13:00",
    endTime: "16:00",
    venueName: "Kallio District",
    address: "",
    city: "Helsinki",
    pricingType: "free",
    price: null,
    capacity: "40",
    coverImage: "https://images.unsplash.com/photo-1758030306457-e54f25fe4384?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXQlMjBhcnQlMjBncmFmZml0aSUyMG11cmFsfGVufDF8fHx8MTc3MTg4MTcyOHww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Helsinki Art Tours",
    organizerEmail: "tours@helsinkiart.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-02-06T10:00:00.000Z",
  },
  {
    id: "event_028",
    title: "Midsummer Music Festival",
    description: "Celebrate Juhannus with live music, bonfires, and traditional Finnish festivities on the beautiful Seurasaari Island.",
    category: "Festival",
    tags: ["midsummer", "festival", "traditional"],
    startDate: "2026-06-19",
    endDate: null,
    startTime: "16:00",
    endTime: "02:00",
    venueName: "Seurasaari Island",
    address: "",
    city: "Helsinki",
    pricingType: "paid",
    price: "42",
    capacity: "1500",
    coverImage: "https://images.unsplash.com/photo-1573463908761-567b9356c64f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvdXRkb29yJTIwbXVzaWMlMjBmZXN0aXZhbCUyMHN0YWdlfGVufDF8fHx8MTc3MTg0ODYxN3ww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Helsinki Events Oy",
    organizerEmail: "midsummer@helsinkievents.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-02-07T10:00:00.000Z",
  },
  {
    id: "event_029",
    title: "Contemporary Design Showcase",
    description: "Showcasing the latest in Finnish design — furniture, fashion, ceramics, and digital art. Meet the designers and shop directly.",
    category: "Art",
    tags: ["design", "showcase", "contemporary"],
    startDate: "2026-04-16",
    endDate: null,
    startTime: "12:00",
    endTime: "19:00",
    venueName: "Design Museum",
    address: "",
    city: "Helsinki",
    pricingType: "paid",
    price: "16",
    capacity: "250",
    coverImage: "https://images.unsplash.com/photo-1761403757058-e3c95b662a89?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcnQlMjBnYWxsZXJ5JTIwZXhoaWJpdGlvbiUyMG1vZGVybnxlbnwxfHx8fDE3NzE5MDIzOTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Design Museum Helsinki",
    organizerEmail: "info@designmuseum.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-02-08T10:00:00.000Z",
  },
  {
    id: "event_030",
    title: "Children's Science Adventure Day",
    description: "A day of discovery for young minds! Interactive experiments, planetarium shows, and robot building workshops for ages 5-12.",
    category: "Kids",
    tags: ["science", "children", "educational"],
    startDate: "2026-06-07",
    endDate: null,
    startTime: "10:00",
    endTime: "15:00",
    venueName: "Heureka Science Centre",
    address: "",
    city: "Vantaa",
    pricingType: "paid",
    price: "12",
    capacity: "300",
    coverImage: "https://images.unsplash.com/photo-1707696544753-cf8af7babeee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxraWRzJTIwcGxheWdyb3VuZCUyMGNhcm5pdmFsfGVufDF8fHx8MTc3MTk1NzI3N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    organizerName: "Heureka Foundation",
    organizerEmail: "kids@heureka.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    attendees: 0,
    createdAt: "2026-02-09T10:00:00.000Z",
  },
  // ── Home page "Upcoming Events" section ──
  {
    id: "event_upcoming_1",
    title: "OLKA activities Central Ostrobothnia",
    description: "Volunteer-led peer support activities at the hospital. Coffee, conversation, and communal warmth for patients and visitors alike.",
    category: "Support",
    tags: ["volunteer", "community", "health"],
    startDate: "2026-03-09",
    endDate: null,
    startTime: "16:00",
    endTime: "19:30",
    venueName: "Central Ostrobothnia Central Hospital",
    address: "Mariankatu 16-20",
    city: "Kokkola",
    pricingType: "free",
    price: null,
    capacity: "100",
    coverImage: null,
    organizerName: "OLKA Volunteers",
    organizerEmail: "olka@kokkola.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    upcoming: true,
    attendees: 0,
    createdAt: "2026-02-10T10:00:00.000Z",
  },
  {
    id: "event_upcoming_2",
    title: "Christmas Concert - Jenni Taivassalo",
    description: "Celebrate the holiday season with an intimate Christmas concert by acclaimed vocalist Jenni Taivassalo at the historic Kaarlelan Church.",
    category: "Festival",
    tags: ["christmas", "concert", "holiday"],
    startDate: "2026-12-23",
    endDate: null,
    startTime: "19:00",
    endTime: "20:00",
    venueName: "Kaarlelan kirkko",
    address: "Kruunupyyntie 1",
    city: "Kokkola",
    pricingType: "paid",
    price: "20",
    capacity: "200",
    coverImage: null,
    organizerName: "Kokkola Events",
    organizerEmail: "concerts@kokkola.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    upcoming: true,
    attendees: 0,
    createdAt: "2026-02-11T10:00:00.000Z",
  },
  {
    id: "event_upcoming_3",
    title: "Dallapé - Finnish music legend",
    description: "Live performance by the legendary Dallapé orchestra, Finland's most beloved music ensemble since 1925. A night of nostalgia and joy.",
    category: "Music",
    tags: ["orchestra", "finnish", "legend"],
    startDate: "2026-02-14",
    endDate: null,
    startTime: "18:00",
    endTime: "20:00",
    venueName: "Snellman Hall",
    address: "Vingonkatu 18",
    city: "Kokkola",
    pricingType: "paid",
    price: "15",
    capacity: "250",
    coverImage: null,
    organizerName: "Kokkola Cultural Society",
    organizerEmail: "culture@kokkola.fi",
    organizerPhone: "",
    website: "",
    status: "approved",
    featured: false,
    upcoming: true,
    attendees: 0,
    createdAt: "2026-02-12T10:00:00.000Z",
  },
];