/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ceucfqrlnvepkizlzpkr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNldWNmcXJsbnZlcGtpemx6cGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNDM1NDAsImV4cCI6MjA4NzcxOTU0MH0.EzuA9hPOwb9Ekd0FUDag0y-PN74S57Rmj8-m7yrS15U"